apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: harbor.mbentley.net/docker.io/library/nginx:latest
      ports:
        - containerPort: 80