apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-headlamp
  namespace: addons-testing # Your vSphere namespace
spec:
  addonRef:
    name: headlamp
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: workload-vsphere-vks1
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
  name: workload-vsphere-vks1-headlamp
  namespace: addons-testing # Your vSphere namespace
spec:
  values:
    gatewayApi:
      enabled: true
      gateway:
        className: istio
        create: true
        name: headlamp-gateway
    hostname: headlamp.192.168.104.106.sslip.io
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-cert-manager
  namespace: addons-testing # Your vSphere namespace
spec:
  addonRef:
    name: cert-manager
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: workload-vsphere-vks1
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-prom
  namespace: addons-testing # Your vSphere namespace
spec:
  addonRef:
    name: prometheus
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: workload-vsphere-vks1
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
  name: workload-vsphere-vks1-prometheus
  namespace: addons-testing # Your vSphere namespace
spec:
  values:
    deploycomponents:
      kube-state-metrics: true
      node-exporter: true
      pushgateway: false
      prometheus: true
      alertmanager: false
      prometheus-operator: true
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-istio
  namespace: addons-testing # Your vSphere namespace
spec:
  addonRef:
    name: istio
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: workload-vsphere-vks1
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
  name: workload-vsphere-vks1-istio
  namespace: addons-testing  # Your vSphere namespace
spec:
  values:
    istio:
      namespace: "istio-system"
      ambientMode:
        enabled: false
      istioCNI:
        enabled: false
      gateways:
        egress:
          enabled: false
        ingress:
          enabled: true
          namespace: "istio-system"
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 5
      pilot:
        replicas: 1
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 2
      meshConfig:
        enableTracing: false
        accessLogFile: ""
        meshID: "workload-vsphere-vks1"
        