k get cm -A | grep nfs-client
    vmware-system-tkg                    demo-cl01-nfs-client.app                                1      114m
    vmware-system-tkg                    demo-cl01-nfs-client.app-change-mdlg6                   1      114m
---
k logs pod/csi-nfs-controller-6fd98779c8-g58wv -n nfs-client -c nfs
I0715 20:06:25.995052       1 nfs.go:90] Driver: nfs.csi.k8s.io version: N/A
I0715 20:06:25.995335       1 nfs.go:148] 
DRIVER INFORMATION:
-------------------
Build Date: N/A
Compiler: gc
Driver Name: nfs.csi.k8s.io
Driver Version: N/A
Git Commit: N/A
Go Version: go1.26.3-X:boringcrypto
Platform: linux/amd64

---

# VKS Add-on: NFS Client Provisioner

# controller:
#   nodeSelector:
#   resources:
#     csi-provisioner:
#       limits:
#         cpu: ""
#         memory: 400Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
#     csi-resizer:
#       limits:
#         cpu: ""
#         memory: 400Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
#     csi-snapshotter:
#       limits:
#         cpu: ""
#         memory: 200Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
#     liveness-probe:
#       limits:
#         cpu: ""
#         memory: 100Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
#     nfs:
#       limits:
#         cpu: ""
#         memory: 200Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
# namespace: nfs-client
# nfs:
#   path: /nfs-storage
#   server: ""
# node:
#   resources:
#     liveness-probe:
#       limits:
#         cpu: ""
#         memory: 100Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
#     nfs:
#       limits:
#         cpu: ""
#         memory: 300Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
#     node-driver-registrar:
#       limits:
#         cpu: ""
#         memory: 100Mi
#       requests:
#         cpu: 10m
#         memory: 20Mi
# nsLimitRange:
#   defaultRequests:
#     cpu: 10m
#     memory: 20Mi
# storageClass:
#   create: true
#   defaultClass: "false"
#   name: example-ss-nfs-client
# storageClasses: []
