# Put static here.  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: //nfsshare
    server: 10.110.72.149 # Your NFS Server IP from kubectl get service nfs-server-test-service 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Must be empty to bind with the static PV
  resources:
    requests:
      storage: 50Gi
