apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vks-02
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: builtin-generic-v3.5.0
    version: v1.33.3---vmware.1-fips-vkr.1
    variables:
      - name: kubernetes
        value:
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: nfs-datastore-policy
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: nfs-datastore-policy
          replicas: 2
      