apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachineService
metadata:
  name: new-vm-lb-h2gg
  namespace: vcfa-ns-mgsnf
spec:
  selector:
    new-vm-lb-h2gg: vm-lb-selector
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: sql
      protocol: TCP
      port: 3306
      targetPort: 3306
