apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachineService
metadata:
  name: vks01-ssh
spec:
  selector:
    capv.vmware.com/cluster.name: kc-chris-1
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
